[tool.poetry]
name = "app"
version = "0.1.0"
description = "Plataforma médica para Medintegral IPS SAS"
authors = ["Sergio Majé <smajefranco@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.scripts]
app = { callable = "app:run" }

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.95.0"}
pydantic = {extras = ["email"], version = "^1.10.4"}
sqlalchemy = "1.4.46"
psycopg2 = "^2.9.5"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
sqlalchemy-utils = "^0.39.0"
emails = "^0.6"
fastapi-camelcase = "^1.0.5"
phonenumbers = "^8.13.5"
aiofiles = "^23.1.0"


[tool.poetry.group.dev.dependencies]
sqlalchemy-stubs = "^0.4"
mypy = "^0.991"
isort = "^5.12.0"
pylint = "^2.16.1"
flake8 = "^6.0.0"
black = "^23.1.0"
types-aiofiles = "^23.1.0.1"

[tool.isort]
line-length = 90

[tool.black]
line-length = 90
target-version = ['py310']
skip-string-normalization = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
