-- In this file finds the configurations
-- for the person.person generated by SQLAlchemy.

-- Chage dni type from serial to integer
alter table person.person alter column dni type integer;

-- drop value default for dni column
alter table person.person alter column dni drop default;

-- drop sequence for dni column
drop sequence person.person_dni_seq;